name: ci
on: [pull_request]

jobs:
  run:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Run Test
        run: make test
